server:
  port: 8080
spring:
  datasource:
    name: vote
    username: lxh
    password: 123456
    url: jdbc:mysql://106.15.190.231:3306/pingjiao?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    check-template-location: true
  mvc:
      static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml